### ISSUE TITLE
[Siddhi Editor] [Bug] User can export file without having saved

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#160]
**M3**

**Steps to Recreate:**
1. Open a siddhi file on the editor and do changes(now be focused on an unsaved file) 
2. Check export file menu option
3. And click on Ctrl+E shortcut option

**Actual Result:**
File>>Export menu option is disabled but shortcut option is working and the user can export an unsaved file.

**Expected Result:**
Shortcut option also should be disabled when file is unsaved

**Comment by dnwick** [comment]
@chaminda I checked on the current editor but cannot see a issue. Can you please verify

**Comment by dnwick** [comment]
@chaminda found the issue exist in one flow. Fixed in latest.
