### ISSUE TITLE
Inadequate information on GDPR section

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#288]
**Description:**
Section[1] only focuses on forgetme feature as GDPR compliancy of the product so please include cookie handling part as well. 
**NOTE:** Adding this for tracking the requested improvement while there is a note saying the 'section is in progress'
[1]
https://docs.wso2.com/display/DAS3xx/General+Data+Protection+Regulations+for+WSO2+Data+Analytics+Server

**Suggested Labels:**
Documentation, 3.2.0

**Suggested Assignees:**
@RukshiW

**Comment by RukshiW** [comment]
Added [1] for SP. The DAS docs will be updated with a similar page.

[1] https://docs.wso2.com/display/SP4xx/Handling+Cookies
