### ISSUE TITLE
Typo on Advanced label in Persist Event Stream section

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#289]
**Description:**
Typo on Advanced label in Persist Event Stream section.
Please see the below screen

![image](https://user-images.githubusercontent.com/7115693/37148298-f31ba748-22ef-11e8-88e3-aef71c986957.png)

**Affected Product Version:**
wso2das-3.2.0-alpha

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-analytics-common/pull/521
