### ISSUE TITLE
streams.json file path is differed in the document

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#296]
**Description:**
Actual directory where streams.json layed is "repository/components/tools/identity-anonymization-tool/conf/streams/streams.json" but document[1] mentioned it by omitting 'streams' part for the path.

[1] https://docs.wso2.com/display/DAS3xx/General+Data+Protection+Regulations+for+WSO2+Data+Analytics+Server

**Affected Product Version:**
wso2das-3.2.0-alpha2

**Comment by pcnfernando** [comment]
Updated the document to point to the correct path in [1].

[1] https://docs.wso2.com/display/DAS3xx/General+Data+Protection+Regulations+for+WSO2+Data+Analytics+Server

**Comment by chaminda** [comment]
Tested on beta pack and the fix has been missed there.

**Comment by chaminda** [comment]
Verified hence closing the issue
