### ISSUE TITLE
Provide with a sample configuration in default streams.json file

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#297]
**Description:**
streams.json file should be included with sample configuration with default json placeholders 
Currently, the file has an empty array without default elements which are explained in [1].

[1] https://docs.wso2.com/display/DAS3xx/General+Data+Protection+Regulations+for+WSO2+Data+Analytics+Server

**Affected Product Version:**
wso2das-3.2.0-alpha2

**Comment by sajithshn** [comment]
Fixed with PR https://github.com/wso2/identity-anonymization-tool/pull/59. Fix will be made available with version 3.2.0-beta

**Comment by chaminda** [comment]
Verified on beta pack the fix has been missed.

**Comment by sajithshn** [comment]
Could you please check that on RC1

**Comment by chaminda** [comment]
Verified on RC2 hence closing the issue
