### ISSUE TITLE
Product doc is redirecting to an older version

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#303]
**Description:**
Once click on Doc link it redirecting to the old doc space[1]. Please point this to the new space.

![image](https://user-images.githubusercontent.com/7115693/37339788-d59d5e78-26e1-11e8-8703-f1f549f6fbb8.png)

[1] https://docs.wso2.com/display/DAS310/WSO2+Data+Analytics+Server+Documentation

**Affected Product Version:**
wso2das-3.2.0-beta

**Comment by pcnfernando** [comment]
Fixed with [wso2/product-das/#326](https://github.com/wso2/product-das/pull/326)
