### ISSUE TITLE
No information on the two stream files in streams directory

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#316]
**Description:**
There are two stream files as **das-streams.json** and **is-streams.json** in streams folder inside the tool. Document doesn't have information on those.

**Affected Product Version:**
wso2das-3.2.0-RC1

**Comment by sajithshn** [comment]
We will be removing the is-streams.json from the pack. Fix will be available with RC2

**Comment by sajithshn** [comment]
Fixed with https://github.com/wso2/product-das/pull/321. Now DAS will only contain das-streams.json

**Comment by chaminda** [comment]
@RukshiW please add this information to the documentation as well.
