### ISSUE TITLE
Relative path not working for log-file-path in config.json of forget-me tool

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#319]
**Description:**
Relative path not working for log-file-path in config.json of forget-me tool
"log-file-path" : "../../../../logs"
**Affected Product Version:**

**OS, DB, other environment details and versions:**    
macOs, jdk1.8

**Steps to reproduce:**
1. configure config.json providing the relative path to logs file location. 
"log-file-path" : "../../../../logs"
2. run the forget-me.sh tool
temporary logs are not generated.

**Comment by pcnfernando** [comment]
The relative path should be provided relative to <CARBON_HOME>.

**Comment by chaminda** [comment]
Working when give the path relative to the ${CARBON_HOME}
