### ISSUE TITLE
Anonymization on log files doesn't work as expected.

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#320]
**Description:**
Anonymization on log files doesn't work as expected. 
log-file type processor has been enabled in config.jogs and log-file-path has also been updated.
Once run the forget-me.sh temporary logs were generated but provided name hadn't updated.

```
TID: [-1234] [] [2018-03-15 11:04:18,652]  WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  Failed Administrator login attempt 'dash[-1234]' at [2018-03-15 11:04:18,652+0530] {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil}
```

**Affected Product Version:**
wso2das-3.2.0-RC1

**OS, DB, other environment details and versions:**    
macOS, jdk1.8.0_152, H2

**Steps to reproduce:**
1. Configure/enable config.json with log-file type processor. 
2. Delete an user from the server.
3. Run the forget-me.sh tool
4. Verify the log files whether removed user's references(name) is there
Removed user's references can be found in the log

**Comment by pcnfernando** [comment]
Added the pattern with PR [#71](https://github.com/wso2/identity-anonymization-tool/pull/71)

**Comment by sajithshn** [comment]
Will be fixed in RC2
