### ISSUE TITLE
Spark version included and how to update it

### ISSUE THREAD

**Issue by adeze** [wso2/product-das#33]
Hi,
i'm just getting started with DAS, but i've noticed that in the spark sql console, it reports back as being version 1.3 (i'm assuming this is Spark 1.3)..
spark 1.5.2 is the most recent build, and so i'm wondering how/when this can be updated?
or do i have to attach DAS to a local client instance by modifying spark-defaults.conf with 
```
carbon.spark.master=client
```

**Comment by nirandaperera** [comment]
Hi Adeze, 

In the DAS GA release we are using SPark 1.4.1 by default. Seems like what you have mentioned is a UI glitch. 

And yes, you can connect to an external spark cluster by modifying the spark-defaults.conf file. Refer the docs [1]

[1] https://docs.wso2.com/display/CLUSTER44x/Spark+Deployment+Patterns#SparkDeploymentPatterns-Clientmode

**Comment by adeze** [comment]
thanks--  1.4.1 was the minimum version i needed anyway  --any idea when a 1.5.2+ version will be released?is there way (or hack) to update it in client mode (for dev) or does this require building from source ?
