### ISSUE TITLE
das and bam

### ISSUE THREAD

**Issue by FS1360472174** [wso2/product-das#56]
1.das provide same function as BAM?and it replaces BAM?

2.I want to archive cassandra data,but can not find the parameter of "external cassandra cluster" in BAM2.5,seems that it remove this param.
so I do confuse about the meaning of archiving cassandra data.we still store the data in this cassandra cluster.
by the way,how to deal with when you need to visit the archived data.

**Comment by lafernando** [comment]
Hi,

Yes, DAS replaces the functionality given by BAM. For more info, check docs at https://docs.wso2.com/display/DAS301/WSO2+Data+Analytics+Server+Documentation.

And now, Cassandra is just one of the several data connectors we support in DAS, for Cassandra configuration, check https://docs.wso2.com/display/DAS301/Configuring+Data+Persistence+With+Cassandra.

Cheers,
Anjana.
