### ISSUE TITLE
ML Siddhi Extension not present in DAS 3.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by ardneh** [wso2/product-das#74]
Hi,

We have been quite excited to get the Machine Learner bundled with DAS.  When trying out wso2das-3.1.0-20160727.210657-61.zip it does not appear that the ML Siddhi Extension is installed (it is not in the installed features list under "Feature Management" and an "No extension exist for StreamFunctionExtension{namespace='ml'}  in execution plan" exception is thrown when trying to use #ml:predict() on a stream).  I also tried installing version 1.1.1 of the extension via the wilkes repository but I still get the "No extension exist..." exception.

Would it be possible to get the ML Siddhi Extension bundled with DAS 3.1.0?  It would be very convenient to have it pre-installed.  If not, when will there be a compatible version of the extension available for DAS 3.1.0 or where can I find one to try it out now?

Thanks!

**Comment by wggihan** [comment]
Hi ardneh,

Apologized for not update you sooner. We have added ML Siddhi extension to the DAS 3.1.0 RC1 after your request. But it seems to be there was an integration issue with that. But now all issues are sorted out. We are planing to release RC2 in next release. If it urgent, you can find a nightly build DAS 3.1.0 SNAPSHOT pack from our Jenkins server using below link.

https://wso2.org/jenkins/view/product-builds/job/product-das/lastStableBuild/org.wso2.das$wso2das/

Cheers.

**Comment by ardneh** [comment]
Thanks, we will give that a try!
